version: "2.4"

services:
  mps-app-1:
    restart: always
    container_name: mps-app-1
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - APP_MONGODB_URI=mongodb://mongodb:27017
      - APP_DB=test-db
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  mps-app-2:
    restart: always
    container_name: mps-app-2
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - APP_MONGODB_URI=mongodb://mongodb:27017
      - APP_DB=test-db
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped

