version: "2.4"

services:
  mps-app:
    restart: always
    container_name: mps-app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - APP_HOST=localhost
      - APP_PORT=8080
      - APP_MONGODB_URI=mongodb:localhost:27017
      - APP_DB=test-db
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

